### ISSUE TITLE
Scripted test to upload a file and check it is imported

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-aircan#26]
When developing AirCan i want a scripted test I can run to test the end to end functioning of a load of data into DataStore

## Acceptance

* [ ] Create a dataset in CKAN test instance
* [ ] Create resource with a file (link out to file online e.g. in github or in storage)
* [ ] Check on status of run using {ckan instance}/api/3/aircan_status
* [ ] Check datastore is updated (called data API): ... /api/3/datastore_search ...

## Tasks

...

**Comment by leomrocha** [comment]
Latest discussion Q&A:

- Where do we put the “test” scripts: ckanext-aircan
- Does it get run automatically? Manually run for now
- Can you configure the ckan instance to run against? Yes! Default prob local ckan instance (e.g. localhost:5000) and put in README about the standard test ckan instance we have …
- How do I do local development/testing?
  - Just test the microservices
  - Test for integration by deploying into the cloud quickly and with automated integration tests
