### ISSUE TITLE
Support for Airflow v2 

### ISSUE THREAD

**Issue by shubham-mahajan** [datopian/ckanext-aircan#31]
When the user is using `ckanext-aircan` with airflow it should be able to use it with the latest version(v2).

## Acceptance Criteria

* [x] `ckanext-aircan` is compatible with airflow v2

## Tasks

* [x] Identify the changes
* [x] Implement the changes
